[package]
name = "integration-test"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tempfile = "3.9"
fs_extra = "1.3"
ureq = "2.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
exponential-backoff = "1.2"
libherokubuildpack = { version = "0.17", features = ["command"] }
