[package]
name = "integration-test"
edition = "2021"
rust-version = "1.75"

[dependencies]
exponential-backoff = "1"
fs_extra = "1"
libherokubuildpack = { version = "0.17", features = ["command"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
ureq = "2"
