version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  openjdk-8:
    docker:
      - image: cimg/openjdk:8.0
  openjdk-11:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  maven:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - heroku/install
      - checkout
      - run: ./mvnw clean install -Pit
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  ci:
    jobs:
      - maven:
          matrix:
            parameters:
              executor: ["openjdk-8", "openjdk-11"]
